db/02-schema-upgrade.sql
=> Drop unnecessary wkb_geometry95 column

.github/workflows/codeql.yml
Run the analysis on friday morning instead of evening.
=> Update CodeQL workflow schedule

db/03-gis-views.sql
=> Add GIS views

.github/workflows/ci.yml, Directory.Build.props
=> Treat warnings as errors during CI build

.github/workflows/pre-release.yml, .github/workflows/release.yml, Dockerfile, README.md
=> Build and push docker image

db/04-export-view.sql
=> Add data export view

db/02-schema-upgrade.sql
We don't need a settings table at the moment.
#5
=> Remove obsolete settings table

src/ClientApp/src/components/MainMap.js, src/EwsContextExtensions.cs, tests/ExportControllerTest.cs, tests/StandortControllerTest.cs
=> Do not display null geometries

.github/workflows/trivy.yml
=> Add missing build args

.github/workflows/trivy.yml, Dockerfile
=> Fix critical security vulnerabilites

config/pgadmin4-servers.json, db/05-user-table.sql, docker-compose.yml, src/EwsContext.cs, src/EwsContextExtensions.cs, src/Models/User.cs, src/Models/UserRole.cs
=> Add user table

.editorconfig, Directory.Build.props, src/Controllers/DataServiceController.cs, src/DataServiceResponse.cs, src/Program.cs, tests/DataServiceControllerTest.cs, tests/EWS.Test.csproj
=> Add endpoint for accessing the Data Service API

src/Program.cs, tests/ContextFactory.cs
See https://go.microsoft.com/fwlink/?linkid=2134277 for details.
Simplify retrieving the db context on app startup along the way.
=> Configure QuerySplittingBehavior on db context

src/Controllers/DataServiceController.cs, tests/DataServiceControllerTest.cs
=> Add (temporary) endpoint for migrating Gemeinde data

src/ChangeTrackerExtensions.cs, src/ClientApp/src/components/pages/Home.js, src/Controllers/StandortController.cs, src/EwsContextExtensions.cs, src/Program.cs, tests/EwsContextTest.cs, tests/Initialize.cs, tests/StandortControllerTest.cs, tests/UserControllerTest.cs
See https://www.npgsql.org/efcore/release-notes/6.0.html#timestamp-rationalization-and-improvements for details.
=> Use legacy timestamp behavior of Npgsql

src/Controllers/ExportController.cs, tests/ContextFactory.cs, tests/ExportControllerTest.cs
=> Fix data export

src/ClientApp/src/components/MainMap.js, src/ClientApp/src/components/Popup.js
=> Update popup info

src/ClientApp/src/components/MainMap.js
=> Initially fit to kanton extent

src/ClientApp/cypress/integration/home.spec.js, src/ClientApp/src/components/Search.js, src/ClientApp/src/components/pages/Home.js, src/Controllers/StandortController.cs
=> Correctly handle null values in Gemeinde dropdown

docs/articles/einstiegsseite.md, src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/DetailMap.js, src/ClientApp/src/components/StandortForm.js
=> Koordinaten aus karte

src/EWS.csproj, src/Program.cs
=> Use Extern policy as fallback

src/ClientApp/src/components/SearchResults.js
=> Fix column width in search results

src/ClientApp/src/components/DateUserInputs.js, src/ClientApp/src/components/StandortForm.js
=> Standort freigabe

src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/DateUserInputs.js, src/ClientApp/src/components/StandortForm.js
=> Fix form not updating by removing defaultValues in form

src/ClientApp/cypress/integration/bohrprofilform.spec.js, src/ClientApp/src/components/Search.js
=> Fix date search

docs/docfx.json, src/ClientApp/src/components/Layout.js
=> Directly link to first help article

src/ClientApp/src/components/MainMap.js, src/ClientApp/src/components/pages/Home.js
=> Fit map to search results

src/ClientApp/src/components/SearchResults.js
=> Reset page count on search

src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/Layout.js, src/ClientApp/src/components/StandortForm.js, src/ClientApp/src/components/ZoomToLatestControl.js
Resolves #113
Resolves #119
Resolves #124
=> Update and add missing mouse over texts

src/ClientApp/src/components/Layout.js
=> Refresh page after logout

src/ClientApp/src/components/StandortForm.js
=> Fix defaultvalue of checkbox

src/ClientApp/src/components/MainMap.js
=> Fix padding

src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/StandortForm.js
=> Fix form behaviour with defaultValue, value and setValue

src/ClientApp/src/components/BohrungForm.js
=> Change label of durchmesser input

.editorconfig, Directory.Build.props, src/Authentication/AutoUserRegistrationMiddleware.cs, src/Authentication/CheckAuthorizedMiddleware.cs, src/Authentication/Extensions.cs, src/Authentication/PolicyNames.cs, src/ChangeTrackerExtensions.cs, src/EwsContext.cs, src/EwsContextExtensions.cs, src/Migrations/20220714092836_InitialCreate.cs, src/Migrations/20220714093345_ChangeGemeindeToText.cs, src/Migrations/20220714182758_AddUserTable.cs, src/Migrations/20220715112422_ChangeGrundbuchnummerToText.cs, src/Migrations/EwsContextModelSnapshot.cs, src/Models/Bohrprofil.cs, src/Models/Bohrung.cs, src/Models/Code.cs, src/Models/CodeSchicht.cs, src/Models/CodeTyp.cs, src/Models/EwsModelBase.cs, src/Models/IDateUserSettable.cs, src/Models/IEwsModelBase.cs, src/Models/Schicht.cs, src/Models/Standort.cs, src/Models/User.cs, src/Models/UserRole.cs, src/Models/Vorkommnis.cs
=> Enforce codestyle

src/ClientApp/src/components/Layout.js
=> Reload after logout

src/Controllers/BohrungController.cs, src/Controllers/GemeindeMigrationController.cs, src/DataService.cs, src/Program.cs, tests/BohrungControllerTest.cs, tests/DataServiceControllerTest.cs, tests/EWS.Test.csproj, tests/EwsContextTest.cs
=> Update standort information upon bohrung deletion

src/ClientApp/public/index.html, src/ClientApp/src/components/Layout.js
=> Add meaningful application title

docs/articles/einstiegsseite.md, src/ClientApp/cypress/fixtures/standorteGemeinde.json, src/ClientApp/cypress/integration/schichtenform.spec copy.js, src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/InputForm.js, src/ClientApp/src/components/SchichtForm.js, src/ClientApp/src/custom.css, src/ClientApp/src/setupProxy.js, src/Controllers/BohrprofilController.cs, src/Controllers/CodeSchichtController.cs, src/Controllers/SchichtController.cs, tests/BohrprofilControllerTest.cs, tests/BohrungControllerTest.cs, tests/CodeSchichtControllerTest.cs, tests/SchichtControllerTest.cs
=> Eingabemaske Schicht

src/ClientApp/cypress/integration/home.spec.js, src/ClientApp/src/components/Search.js
=> Do not uri encode gemeinde

src/ClientApp/src/components/DetailMap.js, src/ClientApp/src/components/MainMap.js
=> Fix zoom level

src/ClientApp/src/components/Search.js, src/ClientApp/src/components/pages/Home.js
=> Show reset search button with results

src/ClientApp/src/components/MainMap.js, src/ClientApp/src/components/Popup.js
=> Update info popup

src/ClientApp/src/components/ZoomToLatestControl.js, src/ClientApp/src/custom.css
=> Allow selection on whole map

src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/DetailMap.js
=> Upate form only if currentBohrung contains value

src/ClientApp/src/components/Popup.js
=> Reorder information in info popup

src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/SchichtForm.js, src/ClientApp/src/components/Search.js
Now pressing enter on an autocomplete input applies the first result in the autocomplete suggestion list.
Resolves #167
=> Turn on auto highlighting for all autocomplete inputs

src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/InputForm.js
=> Fix delete function for bohrprofil

src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/DateUserInputs.js, src/ClientApp/src/components/DetailMap.js, src/ClientApp/src/components/SchichtForm.js
=> Field title over field value

src/ClientApp/src/components/Popup.js
=> Use Standort bezeichnung as info window heading

src/ClientApp/cypress/integration/home.spec.js, src/ClientApp/cypress/integration/inputform.spec.js, src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/InputForm.js, src/ClientApp/src/components/SchichtForm.js, src/ClientApp/src/components/SearchResults.js, src/ClientApp/src/components/StandortForm.js, src/ClientApp/src/components/pages/Home.js, src/ClientApp/src/custom.css
=> Enable readonly view for users with role Extern

src/ClientApp/src/components/DetailMap.js
=> Store map resolution before fitting detailMap

src/ClientApp/src/components/BohrungForm.js
=> Fix distance validation

src/ClientApp/src/components/BohrprofilForm.js
=> Update labels and positions to match UI mockup

src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/DetailMap.js
=> Set map to extent of first point of standort

src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/SchichtForm.js
=> Sort autocompletes alphabetically

src/ClientApp/src/components/InputForm.js
=> Do not close current view when saving

src/ClientApp/src/components/SnackbarMessage.js
=> Make snackbar permanent

src/ClientApp/src/components/BohrungForm.js
=> Save date in correct format

src/ClientApp/src/components/InputForm.js
Resolves https://github.com/GeoWerkstatt/ews-boda/issues/204
=> Add close button for form dialog

src/ClientApp/src/components/BohrungForm.js
=> Change update order of form-fields

src/ClientApp/src/components/InputForm.js
=> Add tooltip for dialog close button

src/ClientApp/src/components/DetailMap.js
=> Handle possible null reference

src/ClientApp/src/components/BohrungForm.js
=> Correctly handle unset/invalid date values

src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/DetailMap.js
=> Prevent editing geometries in readonly mode

src/ClientApp/src/components/DateUserInputs.js, src/ClientApp/src/components/StandortForm.js, src/ClientApp/src/components/UserInputForm.js
=> Always show all controls in Standort form

src/ClientApp/src/components/InputForm.js, src/ClientApp/src/components/pages/Home.js
=> Reload Bohrung and Bohrprofil after creating them

src/ClientApp/src/components/BohrungForm.js
=> Update dropdown widths

src/ClientApp/src/components/BohrprofilForm.js
=> Correctly handle date and timezone

src/ClientApp/src/components/DetailMap.js
=> Fix map extent in detailmap for all cases

src/ClientApp/src/components/Layout.js
=> Refresh page on logout

src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/BohrungForm.js
=> Handle datepicker state separately from form state

src/ClientApp/cypress/integration/bohrprofilform.spec.js, src/ClientApp/cypress/integration/home.spec.js, src/ClientApp/cypress/integration/inputform.spec.js, src/ClientApp/cypress/integration/schichtenform.spec.js, src/ClientApp/cypress/integration/user.spec.js, src/ClientApp/cypress/integration/vorkommnisform.spec.js, src/ClientApp/src/components/ConfirmationDialog.js
=> Update button text of confirmation dialog

src/ClientApp/src/components/BohrungForm.js
=> Do not explicitly dirty form when setting coordinates

src/ClientApp/src/components/StandortForm.js, src/ClientApp/src/components/pages/Home.js
=> Set afuUser and afuDatum on client

src/ClientApp/src/components/Layout.js
=> Enable logging out from routes other than search

src/ClientApp/src/components/Layout.js
=> Wait a little to refresh page after logout

src/ClientApp/src/components/MainMap.js
=> Try fix map display

src/ClientApp/src/components/Search.js, src/ClientApp/src/components/SearchResults.js, src/ClientApp/src/components/pages/Home.js
=> Fix pagination

src/ClientApp/src/components/StandortForm.js
=> Move text position

src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/BohrungForm.js
=> Fix layout of Bohrporfil and Bohrung form

src/ClientApp/src/components/SchichtForm.js
=> Sort codeschichten by id

src/ClientApp/cypress/fixtures/standorteGemeinde.json, src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/SchichtForm.js
=> Show text not kurztext

src/ClientApp/src/components/BohrprofilForm.js
=> Sort formation fields by id

src/ClientApp/src/components/Layout.js
=> Refresh with useHistory

src/ClientApp/src/components/VorkommnisForm.js
=> Remove required validation for tiefe

src/ClientApp/src/components/MainMap.js, src/ClientApp/src/components/Popup.js, src/ClientApp/src/components/pages/Home.js
=> Edit Standort from popup

src/ClientApp/src/components/BohrprofilForm.js
=> Fix control position

src/ClientApp/src/components/MainMap.js
=> Reset zoom immediately

src/ClientApp/src/components/MainMap.js, src/ClientApp/src/components/Popup.js, src/ClientApp/src/components/pages/Home.js
=> Correctly update reaonly property for selection

src/ClientApp/src/components/BohrprofilForm.js
=> Sort formationCodes by sortierung

src/ClientApp/cypress/fixtures/bohrung.json, src/ClientApp/cypress/integration/bohrprofilform.spec.js, src/ClientApp/cypress/integration/inputform.spec.js, src/ClientApp/cypress/integration/schichtenform.spec.js, src/ClientApp/cypress/integration/vorkommnisform.spec.js, src/ClientApp/src/components/BohrungForm.js, src/ClientApp/src/components/InputForm.js, src/ClientApp/src/components/StandortForm.js
=> Get Bohrung before editing

src/ClientApp/src/components/BohrungForm.js
=> Dirty form on coordinate change

src/ClientApp/src/components/BohrprofilForm.js, src/ClientApp/src/components/BohrungForm.js
=> Fix save bohrung without date

Dockerfile
=> Remove obsolete health check

src/ClientApp/src/components/Layout.js
=> Update logout url

src/ClientApp/src/components/BohrprofilForm.js
=> Make two inputs fullWidth

Dockerfile, src/ClientApp/package.json
=> Use docfx as global dotnet tool 

.github/workflows/ci.yml, Dockerfile, README.md
=> Update to Node.js 20

.github/workflows/ci.yml, Directory.Build.props, Dockerfile, src/Controllers/ExportController.cs, src/Controllers/StandortController.cs, src/EWS.csproj, src/EwsContextExtensions.cs, src/Program.cs, tests/EWS.Test.csproj, tests/VersionControllerTest.cs
Ändert den Standard-Port des docker Images auf 8080 und lässt den Container als non-root User laufen.
Resolves #323
=> Update to .NET 8

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, .github/workflows/trivy.yml
=> Update github actions

src/EWS.csproj
=> Streamline EF Core versions

src/EwsContext.cs, src/Migrations/EwsContextModelSnapshot.cs
https://github.com/GeoWerkstatt/ews-boda/issues/323
=> Update db model snapshot

.github/workflows/ci.yml, src/ClientApp/package-lock.json, src/ClientApp/package.json
Fixes "ws affected by a DoS when handling a request with many HTTP headers"
=> Bump ws to 7.5.10

src/ClientApp/aspnetcore-https.js
Current actions fail because of this bug.
=> Create folder for https certs, if necessary

.github/workflows/pre-release.yml
Replacing an action that used a deprecated node version.
=> Use GitHub CLI for creating releases
